### ISSUE TITLE
NotImplementedError on USATodayDiversityIndex example

### ISSUE THREAD

**Issue by jensfinnas** [onyxfish/agate#394]
I'm trying to set up my own computation class, but I'm not able to implement the [example in the documentation](http://agate.readthedocs.org/en/1.1.0/cookbook/compute.html#usa-today-diversity-index).

At `table.compute([ ('diversity_index', USATodayDiversityIndex()) ])` I get:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "python2.7/site-packages/agate/table.py", line 933, in compute
    column_types.append(computation.get_computed_data_type(self))
  File "python2.7/site-packages/agate/computations.py", line 38, in get_computed_data_type
    raise NotImplementedError()
NotImplementedError
```

...where `USATodayDiversityIndex` is taken straight from the documentation:

```python
class USATodayDiversityIndex(agate.Computation):
    def get_computed_column_type(self, table):
        return agate.Number()
    def run(self, row):
        super(USATodayDiversityIndex, self).run(row)
        race_squares = 0
        for race in ['white', 'black', 'asian', 'american_indian', 'pacific_islander']:
            race_squares += (row[race] / row['population']) ** 2
        hispanic_squares = (row['hispanic'] / row['population']) ** 2
        hispanic_squares += (1 - (row['hispanic'] / row['population'])) ** 2
        return (1 - (race_squares * hispanic_squares)) * 100
```

Agate version is 1.1.0.

**Comment by onyxfish** [comment]
Doh! Error in the docs! Please change `get_computed_column_type` to `get_computed_data_type`. Then it should work. I'll fix this in the next minor release.
