### ISSUE TITLE
Unicode errors

### ISSUE THREAD

**Issue by Kirkman** [onyxfish/agate#401]
I'm trying to load a series of CSVs into agate so that I can merge them. I'm using Python 2.7, and I have csvkit installed.

Agate keeps choking on some of them. It gives errors along these lines:

`UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 0: invalid continuation byte`

Here are two of the lines that have unicode characters:

`14-038753,2014-08,08/22/2014 23:00,Y, , ,1, , 67701,4,LARCENY-FROM BUILDING UNDER $500,3131,OLIVE ST,37,DOUBLE APPLE CAFÉ AND HOOKAH LOUNGE, ,3131,OLIVE,898807.7,1020477`
`14-038854,2014-08,08/25/2014 14:00,Y, , ,1, , 67601,4,"LARCENY-FROM BUILDING $500 - $24,999",701,CONVENTION PZ,35,AMERICA’S CENTER CONVENTION COMPLEX, ,701,CONVENTION,908773.3,1019107`

Here's a traceback:

    Traceback (most recent call last):
        File "crime-report-parser.py", line 649, in <module>
            main()
        File "crime-report-parser.py", line 638, in main
            clean_files()
        File "crime-report-parser.py", line 93, in clean_files
            agate.Table.from_csv('monthly_files/' + filename, column_names=column_names, column_types=column_types)
        File "/Users/stlrenaj/.virtualenvs/crime/lib/python2.7/site-packages/agate/table.py", line 283, in from_csv
            rows = list(csv.reader(f, **kwargs))
        File "/Users/stlrenaj/.virtualenvs/crime/lib/python2.7/site-packages/agate/csv_py2.py", line 59, in next
            row = next(self.reader)
        File "/Users/stlrenaj/.virtualenvs/crime/lib/python2.7/site-packages/six.py", line 558, in next
            return type(self).__next__(self)
        File "/Users/stlrenaj/.virtualenvs/crime/lib/python2.7/site-packages/agate/csv_py2.py", line 43, in __next__
            return next(self.reader).encode('utf-8')
        File "/Users/stlrenaj/.virtualenvs/crime/lib/python2.7/codecs.py", line 618, in next
            line = self.readline()
        File "/Users/stlrenaj/.virtualenvs/crime/lib/python2.7/codecs.py", line 533, in readline
            data = self.read(readsize, firstline=True)
        File "/Users/stlrenaj/.virtualenvs/crime/lib/python2.7/codecs.py", line 480, in read
            newchars, decodedbytes = self.decode(data, self.errors)

**Comment by Kirkman** [comment]
After lots of hair-pulling, I saw in the docs that I could specify an encoding. Specifying "latin1" solved this issue.
