### ISSUE TITLE
Printing aggregate tables: precision error

### ISSUE THREAD

**Issue by kjam** [onyxfish/agate#412]
Hi @onyxfish ,

Ran into another error (which I believe I ran properly in 1.0.0?) -- unsure this time, sorry :(

```
Traceback (most recent call last):
  File "print_precision_error.py", line 27, in <module>
    agg.print_table()
  File "/home/katharine/.virtualenv/bkreview/local/lib/python2.7/site-packages/agate/table.py", line 1107, in print_table
    print_table(self, max_rows, max_columns, output)
  File "/home/katharine/.virtualenv/bkreview/local/lib/python2.7/site-packages/agate/preview.py", line 85, in print_table
    v = format_decimal(v, format=number_formatters[j])
  File "/home/katharine/.virtualenv/bkreview/local/lib/python2.7/site-packages/babel/numbers.py", line 254, in format_decimal
    return pattern.apply(number, locale)
  File "/home/katharine/.virtualenv/bkreview/local/lib/python2.7/site-packages/babel/numbers.py", line 607, in apply
    rounded = value.quantize(precision, ROUND_HALF_EVEN)
  File "/usr/lib/python2.7/decimal.py", line 2470, in quantize
    'quantize result has too many digits for current context')
  File "/usr/lib/python2.7/decimal.py", line 3872, in _raise_error
    raise error(explanation)
decimal.InvalidOperation: quantize result has too many digits for current context
```

It seems like a simple precision error, but was unable to fix by setting a new context. Do let me know if you find I should set the context another way to get it working, thanks!!

https://gist.github.com/kjam/49cfaeb420ee01af9429

it also uses the other gist (but you'll need to comment out the last line).
https://gist.github.com/kjam/d246a89563b4039d447c

(I'm sure there are much easier ways to replicate, but this is all I have since editing is a .... fun process!)

(please rename the .txt to just be json. GitHub doesn't allow JSON uploads :cry: )

[earth-cleaned.json.txt](https://github.com/onyxfish/agate/files/82622/earth-cleaned.json.txt)

**Comment by onyxfish** [comment]
Have verified this. It is Python 2 specific.

**Comment by onyxfish** [comment]
This was a tricky one, but I think I've got it sorted now!
